### PR TITLE
Support subscriptionPosition for function&sink

### PR DESCRIPTION
**Pull request by jiangpengcheng**
fix: #313

### CODE REVIEW

**Review by nlu90 — APPROVED** [review]

**Review by freeznet — APPROVED** [review]

**Comment by freeznet** [comment]
@jiangpengcheng could you please rebase the master? thanks.

**Comment by jiangpengcheng** [comment]
@freeznet rebased

**Comment by Huanli-Meng** [comment]
@jiangpengcheng do we need to update docs for this PR? Thanks.

**Comment by jiangpengcheng** [comment]
> @jiangpengcheng do we need to update docs for this PR? Thanks.

yes

**Comment by Huanli-Meng** [comment]
Confirm with Pengcheng, no need to update the doc for this PR.

**Pull request merged**
