### PR TITLE
Fix function list return duplicate data error

### PR DESCRIPTION
**Pull request by jiangpengcheng**
fix: #450

### CODE REVIEW

**Comment by imaffe** [comment]
LGTM, thought I don't have permission to approve XD.

**Review by tpiperatgod — COMMENTED** [review]
do we need to remove the deprecated one...

**Comment by tpiperatgod** [comment]
> do we need to remove the deprecated one...

maybe it should be changed in another PR

**Review by tpiperatgod — APPROVED** [review]

**Comment by tpiperatgod** [comment]
and would it be more appropriate to de-duplicate resources based on their names?

**Review by nlu90 — APPROVED** [review]

**Review by freeznet — APPROVED** [review]

**Pull request merged**
